### ISSUE TITLE
doc search todo

### ISSUE THREAD

**Issue by cldougl** [plotly/documentation#817]
**functionality**
- [x] search results should disappear when search bar is erased/empty
- [ ] https://github.com/plotly/documentation/issues/816
- [x] makefile to update indices 
- [x] README describing how to update indices 

**style**
- [x] style search bar
- [x] larger text
- [ ] add search 'tips' under header

**languages**
- [x] add js search
- [x] add python search
- [x] add python search
- [x] add r search
- [x] add ggplot2 search
- [ ] add matlab search
- [x] add dash search
- [x] add pandas to python db
- [x] add references pages
- [x] search pg recursive schema

**content**
- [x] python add dash link & remove old dashboard results
